
* Vorwissenschaftliche Arbeit mit LaTeX

** Was soll das hier?

Ab 2014 müssen Österreichs AHS-Schüler im Zuge der Reifeprüfung
„Vorwissenschaftliche Arbeiten“ (kurz: VWA) erstellen. Vom [[http://www.mnukk.gv.at][Ministerium]]
gibt es diverse Informationen dazu auf: http://www.ahs-vwa.at/

Neben dem Klassiker Microsoft Word [[http://www.ahs-vwa.at/pluginfile.php/31/mod_data/content/1079/WORD_und_VWA.pdf][(Hinweise zu Word und VWA]]) gibt es
noch zahlreiche [[http://windows.iusethis.com/tag/wordprocessor][andere Softwareprodukte]], die das Erstellen einer VWA
ermöglichen.

Wissenschaftliche Dokumente wie [[https://de.wikipedia.org/wiki/Wissenschaftliche_Publikation][Papers]] oder Abschlussarbeiten für
Bachelor, Master oder gar eine Dissertation werden sehr oft mit LaTeX
(sprich: „latech“) gesetzt. Da LaTeX ein Profi-Werkzeug ist, erfordert
es einigen Einarbeitungsaufwand.

*HINWEIS*: Ohne entsprechendes LaTeX-Hintergrundwissen, das zum
Beispiel hervorragend von http://LaTeX.TUGraz.at vermittelt wird, ist
diese Vorlage hier *nicht* zu empfehlen.

Wer jedoch bereits LaTeX-Wissen vorweisen kann, der wird vermutlich
mit der hier beschriebenen Vorlage ein ausgezeichnetes Ergebnis mit
minimalem Aufwand erreichen.

** Wie sieht sowas aus?

In diesem Repository sind zwei PDF-Dateien beigefügt. Die Datei
[[https://github.com/novoid/LaTeX-KOMA-VWA/blob/master/VWA-Beispiel_-_150_Prozent_Zeilenabstand.pdf][VWA-Beispiel_-_150_Prozent_Zeilenabstand.pdf]] beinhaltet eine
Beispiel-VWA mit dem erweiterten Zeilenabstand. Die Datei
[[https://github.com/novoid/LaTeX-KOMA-VWA/blob/master/VWA-Beispiel_-_normaler_Zeilenabstand.pdf][VWA-Beispiel_-_normaler_Zeilenabstand.pdf]] beinhaltet die selbe VWA,
nur mit einem normalen Zeilenabstand.

Die [[http://www.bmukk.gv.at/medienpool/22700/reifepruefung_ahs_lfvwa.pdf][Handreichung]] bezeichnet Einstellungen wie »Zeilenabstand 1 1/2«
als »wirk[t] positiv auf die Lesbarkeit«. Ich interpretiere das
keinesfalls als eine Muss-Vorgabe und würde mich persönlich (in
Absprache mit meinem Betreuer!) für einen normalen Zeilenabstand
entscheiden.

Für Umsteiger von Word oder anderen [[https://de.wikipedia.org/wiki/Wysiwyg][WYSIWYG]]-Programmen wirkt der LaTeX
[[https://de.wikipedia.org/wiki/Satzspiegel][Satzspiegel]] (Text-zu-Ränder-Verhältnisse) ungewohnt großzügig. Dieser
große Rand ist bei einspaltigen Dokumenten durchaus gewünscht und im
Gegensatz zu einem 150-Prozent-Zeilenabstand fördert er die Lesbarkeit
tatsächlich. Das Unterbewusstsein muss beim Zeilensprung weniger
anstrengen aufwenden und daher kann sich der Leser mehr auf die
Aufnahme des Inhaltes konzentrieren. Weiters haben Begutachter die
Möglichkeit, den Rand für Notizen und Anmerkungen auf Papier zu
nutzen.

** Kritik an diversen Dokumenten vom Ministerium

Auf http://www.ahs-vwa.at/ gibt es zahlreiche Materialien, die das
Regelwerk rund um die VWA erklären und unterstützen. Leider gibt es
hierbei auch einige Kritikpunkte, die zu Problemen führen können,
sofern man sich an die Materialien hält. Aus diesem Grunde sind in
diesem Abschnitt einige Mängel kurz geschildert.

*** Richtinien zu den formalen Kriterien ([[http://www.ahs-vwa.at/pluginfile.php/31/mod_data/content/547/VWA-Formale-Richtlinien.pdf][PDF]])

Die formalen Kriterien sind nach typographischen Kriterien teilweise
überholt: einseitiges Dokument, typographisch bedenkliche
Seitenrandvorgaben, und so weiter. So etwas ist leider häufig der
Fall, da keine typographisch ausgebildeten Personen an der Definition
entscheidend mitgearbeitet haben oder andere Kriterien als wichtiger
definiert wurden.

Die PDF-Datei ist durch ungenaue Übernahme von den offiziellen
Vorgaben leider nur als fehlerhaft zu bezeichnen: Flattersatz ist im
Gegensatz zu den Angaben sicher nicht zu bevorzugen (da wurde der Text
falsch interpretiert), 1,5-zeiliger Zeilenabstand und Schriftgröße 12
sind gottseidank nicht zwingend vorgeschrieben.

Aber es ist zu begrüßen, dass überhaupt Dokumente „zum Anhalten“
erstellt wurden.

*** VWA Beispieldokument ([[http://www.ahs-vwa.at/pluginfile.php/31/mod_data/content/533/02-VWA-Blindtext-mit-Anhang.pdf][PDF]])

Das Mindestumfang-Dokument hat leider bei den formalen Kriterien
einige Mängel: Seitenzahlen sind recht ungewöhnlich positioniert,
fehlende (aber vorgeschriebene) Bezüge auf Abbildungen im Text,
inkonsistente Abbildungsbeschriftungen (Beschriftung oberhalb und
unterhalb gemischt), inkonsistente Zeilenabstände, sehr „reduziertes“
Literaturverzeichnis (fehlende Verlage, ISBN, und so weiter).

Es ist leider so, dass dieses Vorzeigedokument gemäß den Kriterien
aus der [[http://www.bmukk.gv.at/medienpool/22700/reifepruefung_ahs_lfvwa.pdf][Handreichung mit zahlreichen Zitaten aus den betreffenden
Gesetzesvorlagen]] in vielen Punkten nicht entspricht.

** Was macht diese Vorlage anders?

Weil hier [[http://en.wikipedia.org/wiki/LaTeX][LaTeX]] mit [[http://www.komascript.de/][KOMA Script]] verwendet wird, gibt es viele
Vorteile für die Autoren:

- *Konzentration auf den Inhalt und nicht die Form*
- konsistente Form
- mehr Freude und Unterstützung beim Schreiben der Arbeit
- keine lästigen Word-Fehler wie fehlerhafte Inhaltsverzeichnisse
  oder Datenverlust durch Bugs
- typographisch ansprechendes Ergebnis
- die [[http://latex.tugraz.at/latex/warum][weiteren üblichen Vorteile von LaTeX]]

Bei der Form wurde die [[http://www.bmukk.gv.at/medienpool/22700/reifepruefung_ahs_lfvwa.pdf][Handreichung mit zahlreichen Zitaten aus den
betreffenden Gesetzesvorlagen]] berücksichtigt und im Sinne eines
möglichst schönen Ergebnisses interpretiert.

** Generelles zu dieser Vorlage

Dieses github-Repository enthält keine VWA-Vorlage. Allerdings folgt
weiter unten eine Anleitung, womit eine andere, professionelle
LaTeX-Vorlage für eine VWA in einfachen Schritten (Kochrezept)
adaptiert wird.

Auf https://github.com/novoid/LaTeX-KOMA-template wird eine Vorlage
bereitgestellt, die (nicht nur) von vielen Studierenden an der [[http://www.TUGraz.at][TU Graz]]
für Abschlussarbeiten (Bachelor bis Doktorarbeit) verwendet wird. Sie
ist [[https://github.com/novoid/LaTeX-KOMA-template/blob/master/Template-Documentation.pdf][sehr gut dokumentiert]] und so flexibel ausgelegt, sodass damit
ebenso eine VWA erstellt werden kann.

** Anleitung

*** Beschaffen der [[https://github.com/novoid/LaTeX-KOMA-template][LaTeX-Vorlage]]

In den meisten Fällen wird wohl der [[https://github.com/novoid/LaTeX-KOMA-template/archive/master.zip][Download durch ZIP]] die einfachste
Variante sein.

Sofern [[https://de.wikipedia.org/wiki/Git][git]] bzw. github-Wissen vorhanden ist, kann die Vorlage
alternativ durch folgenden Befehl heruntergeladen werden:
: git clone https://github.com/novoid/LaTeX-KOMA-template.git Meine-VWA

Wie bei LaTeX üblich, empfiehlt sich ein eigener Ordner für das
LaTeX-Dokument mit all seinen Dateien und Unterordnern.

*** Lesen der Dokumentation

Die Vorlage ist ausgelegt auf US-Amerikanisch. Deshalb ist die
Vorgabe (vorerst) Englisch und auch die Dokumentation der Vorlage ist
in englischer Sprache verfasst: [[https://github.com/novoid/LaTeX-KOMA-template/blob/master/Template-Documentation.pdf][Template-Documentation.pdf]]

Nichtsdestotrotz ist so eine Vorlage durchaus ein komplexes
Gefüge. Um nicht unabsichtlich die Form oder die Funktionalität
negativ zu beeinträchtigen, sollen wenige Abschnitte der
Dokumentation gelesen werden.

Hier ist noch keine aktive Änderung der Vorlage notwendig, da für
eine VWA alle Anpassungen in diesem Abschnitt erklärt werden.

*** Prüfen, ob „biber“ funktioniert

Da biblatex/biber eine verhältnismäßig moderne Art der
Literaturverzeichnisgenerierung ist, haben manche LaTeX-Distributionen
(Installation oder Editor) leider noch Probleme.

HINWEIS: Die Installation von biber kann alternativ auch mit einem
biber-Minimaldokument wie [[https://github.com/novoid/koma-biber-minimal-example][das hier]] überprüft werden.

Die Vorlage sollte bereits in diesem (unangepassten) Zustand
kompilieren und eine PDF-Datei erzeugen.

Die Datei [[https://github.com/novoid/LaTeX-KOMA-template/blob/master/Template-Documentation.pdf][Template-Documentation.pdf]] erklärt, wie das funktioniert. Es
ist darauf zu achten, dass ein Literaturverzeichnis und entsprechende
Referenzen erstellt werden. Wenn die Zitate nur aus den (fett
gesetzten) Zitatbezeichnungen (key) bestehen, hat es nicht
funktioniert.

*** Anpassungen: „main.tex“

In der Datei „main.tex“ sind im obersten Bereich alle allgemeinen
Einstellungen der Vorlage untergebracht. Dieser Teil beschreibt alle
notwendigen Anpassungen, die von der Standardwahl abweichen.

**** Einseitiges Dokument

Die Zeile mit der Definition von „\mylaterality“ wird auf folgende
Zeile geändert:
: \newcommand{\mylaterality}{oneside}

**** Bindekorrektur

: \newcommand{\myBCOR}{0mm}

Statt „0mm“ kann hier ein Wert eingegeben werden wie zum Beispiel
„12mm“ oder „1cm“.

Die [[http://www.golatex.de/bindekorrektur-t4189.html][Wahl der korrekten Bindekorrektur]] hängt ausschließlich von der Art
und Weise ab, wie das Werk gebunden wird.

**** Schriftgröße (passt)

Die Vorauswahl mit
: \newcommand{\myfontsize}{12pt}
entspricht bereits der Vorgabe.

**** Zeilenabstand

Die Vorauswahl definiert einen 100 Prozent Zeilenabstand, auf die auch
die Schriften ausgelegt wurden. Statt „1.0“ schreibt hier wegen
„besserer Lesbarkeit“ das Ministerium (leider) „1.5“ (150 Prozent)
vor:
: \newcommand{\mylinespread}{1.5} 

**** Sprache

Für ein deutschsprachiges Werk ist die Vorauswahl durch Änderung der
Reihenfolge auf folgende Zeile zu ändern:
: \newcommand{\mylanguage}{american,ngerman}

Die zuletzt angeführte Sprache ist die Standardsprache, wobei
„ngerman“ die neue deutsche Rechtschreibung aktiviert. Für alle
anderen Sprachen ist hier die Paketdokumentation vom [[http://www.ctan.org/pkg/babel][babel-Paket]] zu
Rate zu ziehen.

Das korrekte Definieren der Sprache ist aus sehr vielen Gründen
wichtig: Silbentrennung, Beschriftung von Dingen wie Bildern und
Dokumentteilen.

Wie man in seine Arbeit Textpassagen mit anderer Sprache einfügt,
entnimm bitte [[https://github.com/novoid/LaTeX-KOMA-template/blob/master/Template-Documentation.pdf][Template-Documentation.pdf]].

**** Zitierstil (passt)

Das Zitieren mit biblatex macht die Anpassungen des Stils sehr
einfach. Diese Vorlage verwendet „authoryear“, das den Vorgaben vom
Ministerium entspricht:
: \newcommand{\mybiblatexstyle}{authoryear}

Alternative Stile finden sich in der wunderbaren [[http://www.math.upenn.edu/tex_docs/latex/biblatex/biblatex.pdf][Dokumentation von
biblatex]].

**** VWA-Titelseite

Die Titelseite wird gemäß folgender Zeile angepasst:
: \newcommand{\mytitlepage}{template/title_VWA}

**** Metadaten

Startend mit der Zeile
: \newcommand{\myauthor}{AUTHOR}
werden die Metadaten des Dokumentes definiert.

Folgende Variablen werden für die VWA benötigt:

- \myauthor ... die/der Autor(in)
- \mytitle ... der Titel der Arbeit
- \mysubject und \mykeywords ... für die Metadaten der genereirten PDF-Datei
- \mystudy ... wird für die Klasse ausgeborgt (zum Beispiel „8C“)
- \myinstitute ... Name der Schule
- \mysupervisor ... die/der Betreuer(in)
- \myhomestreet ... Straße der Schule
- \myhometown ... Ort der Schule
- \myhomepostalnumber ... Postleitzahl der Schule
- \mysubmissionmonth ... Monat der Einreichung
- \mysubmissionyear ... Jahr der Einreichung

Die restlichen Metadaten werden derzeit bei einer VWA nicht verwendet.

**** Selbstständigkeitserklärung

Die voreingestellte Erklärung ...
: \input{template/declaration_TU_Graz}
... wird herausgelöscht. Stattdessen kommt am Ende des Dokumentes vor
...
: \end{document}
... die Selbstständigkeitserklärung nach Wortlaut des
Beispieldokuments vom Ministerium hinein:

: \chapter*{Eidesstattliche Erklärung}
: Ich, \myauthor, erkläre hiermit eidesstattlich, dass ich diese
: vorwissenschaftliche Arbeit selbständig und ohne Hilfe Dritter
: verfasst habe.  Insbesondere versichere ich, dass ich alle wörtlichen
: und sinngemäßen Übernahmen aus anderen Werken als Zitate kenntlich
: gemacht und alle verwendeten Quellen angegeben habe.
: \vfill
: \newcommand{\mysignatureblock}[3]{%
:   \begin{tabular}{llp{2em}l} 
:   #1 & \hspace{3cm}        & & \hspace{4cm} \\\cline{2-2}\cline{4-4}
:      &                     & & \\[-3mm]
:      & {\footnotesize #2}  & & {\footnotesize #3}
:   \end{tabular}
: }
: \mysignatureblock{\myhometown, am}{Datum}{Unterschrift}
: \vfill\vfill

Der Ort wird aus der weiter oben definierten Variable
„\mysubmissiontown“ entlehnt. Wenn er abweichen sollte, bitte
entsprechend in der vorletzten Zeile oben anpassen.

**** Dokumenteinteilung

Abweichend von den VWA-Vorgaben hat die Vorlage eine andere generelle
Struktur. Die dadurch notwendigen Anpassungen sind folgende:

Die Zeilen für den Abstract ...
: \cleardoublepage
: \addcontentsline{toc}{chapter}{Abstract}
: \include{abstract}              %% Abstract
... müssen vor das Inhaltsverzeichnis ...
: \tableofcontents
... verschoben werden.

Das optionale Vorwort kann dahinter gemäß dem Abstract-Beispiel
erstellt werden.

Das Abbildungsverzeichnis ...
: \listoffigures
... wird hinter das Literaturverzeichnis ...
: \printbibliography
... verschoben.

Die Bezeichnung Appendix in ...
: \addpart*{Appendix}
... kann auf „Anhang“ geändert werden:
: \addpart*{Anhang}

Im Anhang (vor der Selbstständigkeitserklärung) werden dann die
Begleit- und Betreuungsprotokolle eingebunden. Soweit hier die
Richtlinie korrekt interpretiert wird, genügt auch ein schlichtes
Beilegen dieser Dokumente.

Weitere optionale Bausteine (Glossar, Abkürzungsverzeichnis, ...)
nach Belieben gemäß der Richtlinien einfügen.

*** Anpassungen: „colophon.tex“

Das [[https://de.wikipedia.org/wiki/Kolophon_%2528Schriftst%25C3%25BCck%2529][Kolophon]] beinhaltet derzeit Hinweise unter anderen auf den
verwendeten Editor. Sofern kein [[https://de.wikipedia.org/wiki/Emacs][GNU/Emacs]] zum Einsatz kam, sollte
entsprechender Hinweis entfernt oder korrigiert werden. 

Weiters ist es ratsam, in einer deutschsprachigen Arbeit, den Text
entsprechend zu übersetzen:
: \newcommand{\mycolophon}{%%
:   Diese Arbeit wurde mit \myacro{GNU}~Emacs geschrieben, in
:   Palatino mit Hilfe von \href{http://LaTeX.TUGraz.at}{pdf\LaTeX2e} und
:   \href{http://en.wikipedia.org/wiki/Biber_(LaTeX)}{\texttt{Biber}} gesetzt.
: 
:   Die \LaTeX{} Vorlage von Karl Voit basiert auf
:   \href{http://www.komascript.de/}{KOMA script} und steht im Internet
:   zum Download bereit: \href{https://github.com/novoid/LaTeX-KOMA-template}{https://github.com/novoid/LaTeX-KOMA-template}
: }

*** Austausch des Logos für die Titelseite: „figures/institution.pdf“

In der Datei ~figures/institution.pdf~ befindet sich derzeit das Logo
der TU Graz. Wenn du diese Datei ersetzt mit ~institution.pdf~ oder
~institution.png~ aus deinem Schul-Logo ersetzt, so wird dies auf der
Titelseite berücksichtigt.

*HINWEIS*: Computer-generierte Grafiken wie Logos oder Screenshots
bitte *niemals* im JPEG-Format speichern. Das ergibt sehr schlechte
Qualität, da JPEG ein verlustbehaftetes Format ausschließlich für
Fotos ist. Siehe auch [[http://latex.tugraz.at/latex/tutorial?s%5B%5D%3Djpg#einfaches_einfuegen_von_bildern][diesen Einschub]].

Wird kein Schul-Logo verwendet, so muss die Datei
~template/title_VWA.tex~ so angepasst werden, dass die Zeile
: \includegraphics[width=3cm]{figures/institution}\\[5mm]
gelöscht oder auskommentiert wird.

*** Deutsche Anführungszeihen statt umgekehrt französischer: „template/typographic_settings.tex“

Wenn du lieber „deutsche Anführungszeichen“ statt »den umgekehrt
französischen Standardanführungszeichen« haben möchtest, so kannst du
in ~template/typographic_settings.tex~ die Zeile:
: \usepackage[babel=true,strict=true,english=american,german=guillemets]{csquotes}
auf folgende Zeile ändern:
: \usepackage[babel=true,strict=true,english=american]{csquotes}

*** Inhalte schreiben

Da nun das Aussehen den formale VWA-Kriterien entspricht, fehlt nur
noch das Wichtigste: der Inhalt.

Hier wird empfohlen, sich vorerst nur auf die Erstellung des Textes
zu konzentrieren. Das ständige Kompilieren des PDF-Ergebnisses lenkt
dabei großteils nur ab und sollte daher nur sporadisch - zum
Beispiel am Ende eines Kapitels - erledigt werden.

Ich wünsche gutes Gelingen bei der VWA!

** Best Practice

Dieser Abschnitt enthält eine Reihe guter Ratschläge zur Erstellung
einer VWA. Wenn auch dir etwas Praktisches einfällt oder ein URL auf
eine wichtige Quelle fehlt, so [[https://github.com/novoid/LaTeX-KOMA-VWA#wie-kann-ich-fehler-oder-vorschlge-zu-dieser-vorlage-kommunizieren][bitte ich um Einsendung]].

*** Wörter zählen

Die Vorgabe laut [[http://www.bmukk.gv.at/medienpool/22700/reifepruefung_ahs_lfvwa.pdf][Handreichung]] ist, dass die Arbeit „zirka 40.000 bis
60.000 Zeichen, inklusive Leerzeichen, exklusive Vorwort, Inhalts-
Literatur- und Abkürzungsverzeichnis“ umfassen soll.

Hierzu werden alle entsprechenden ~tex~-Dateien in einem Text-Editor
geöffnet, der die Zeichen zählen kann. Die Summe entsprechender Werte
ergibt nun eine Schätzung, da die LaTeX-Befehle mitgezählt werden.

Unter Linux gibt es das Tool [[https://en.wikipedia.org/wiki/Wc_%2528Unix%2529][wc]] (word count), das hier gute Dienste
leistet.

** Hilfe

Wenn bei LaTeX mal was nicht so funktioniert, wie es soll, dann gibt
es zahlreiche Möglichkeiten, an Hilfe zu kommen. Wir schlagen
folgende Reihenfolge vor:

1. Fehlermeldung interpretieren lernen und selbst recherchieren
   - Eine Internet-Suchmaschine hilft hier ungemein, indem man die
     konkrete Fehlermeldung in Anführungszeichen eingibt.
2. Kollegen fragen
   - Erfahrenere LaTeX-Benutzer sind eine wunderbare Quelle, die man
     zum Lernen nutzen sollte. Dabei ist zu beachten, dass ein
     gewisses Maß an Fragen nicht überstrapaziert werden
     soll. Die Hilfe eines Kollegen ist nicht kostenlos - sie oder er
     investiert Zeit. Bitte niemals vergessen.
3. Dokumentation
   - Auf [[latex.tugraz.at/dokumentation/links][Webseiten wie diese]] werden gute Dokumentationsquellen
     verlinkt. Ein [[http://latex.tugraz.at/dokumentation/buchempfehlungen][LaTeX-Buch]] kann man kaufen, muss man aber
     nicht. Es gibt genügend LaTeX-Hilfestellungen im Internet,
     sofern man des Englischen mächtig ist.
4. Experten fragen
   - Wer sich mit dem [[https://de.wikipedia.org/wiki/Usenet][Usenet]] auskennt, der kann zum Beispiel in
     news:tu-graz.latex zahlreiche Experten mit einer gut
     formulierten Frage um Hilfe bitten.
     - [[http://michael-prokop.at/internet/newsgroup.html][Einstiegsinformationen Usenet]]
     - [[http://portal.tugraz.at/portal/page/portal/zid/netzwerk/dienste/newsgroups][Infos über die Newsgroups der TU Graz]]

*** Wie man eine Frage richtig stellt

Da man sich von Experten eine gute Antwort erhofft, sollte man auch
so freundlich sein, und die Frage so stellen, dass den Experten keine
unnötige Arbeit entsteht. Das erhöht die Antwortwahrscheinlichkeit.

Dazu muss man lernen, wie man ein Minimalbeispiel erstellt. Das wird
auf http://minimalbeispiel.de/ erklärt.

Witzigerweise kommt man dabei drauf, dass durch die Erstellung eines
Minimalbeispiels, die Lösung zumeist selbst entdeckt wird.

LaTeX-Hindernisse sind ärgerlich. Keine Frage. Jedoch ist das, was man
zur deren Beseitigung lernt, Wissen, das Bestand hat. Jeder
LaTeX-Experte ist nicht von vornherein Experte gewesen. Sie haben
durch ihre Fehler nur bereits mehr Erfahrung als du gemacht.

** Wie kann ich Fehler oder Vorschläge zu dieser Vorlage kommunizieren?

Wenn du dich mit github auskennst, so kannst du mir gerne einen
[[https://github.com/novoid/LaTeX-KOMA-VWA/pulls][pull-request]] zukommen lassen oder [[https://github.com/novoid/LaTeX-KOMA-VWA/issues][ein issue erstellen]].

Ansonsten erreichst du mich per Email unter: LaTeX ät Karl Minus Voit
Punkt at

Sofern es mein Zeitbudget erlaubt, setze ich Verbesserungen gerne um.

** Lizenz

„Vorwissenschaftliche Arbeit mit LaTeX“ is licensed under a
[[https://creativecommons.org/licenses/by-nc-sa/3.0/][Creative Commons
Attribution-NonCommercial-ShareAlike 3.0 Unported License]].
